spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/shelf_scan_cliente
    username: notification_user
    password: notification_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

server:
  port: 8081
